version: '3'

services:
  web:
    profiles:
      - web
    build:
      target: development_build
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - DB_USERS_TEST
    ports:
      - ${POSTGRES_PORT}:5432
  DB_USERS_TEST:
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      -/home/linux/CURSO_DESARROLLO_SOFTWARE/PythonII/FastAPI/DATABASE:/var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-example}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-aitrade}
    ports:
      - '27018:27017'